sudo: required
dist: trusty

language: ruby
rvm: '2.6.3'

addons:
  firefox: "69.0.1"

script:
  - mkdir -p spec && bundle exec rspec spec

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install dbus-x11
  - sudo apt-get install -qq postgresql-server-dev-11.5
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
  - tar -xzf geckodriver-v0.26.0-linux64.tar.gz
  - sudo cp geckodriver /usr/bin

services:
  - postgresql

before_script:
  - psql -c 'create database pgapp_test;' -U postgres

script:
  - xvfb-run make test
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/
